export const schemaTypes = {
  address: [
    { stub: "address.zipCode", label: "Zip Code" },
    { stub: "address.city", label: "City" },
    { stub: "address.cityPrefix", label: "City Prefix" },
    { stub: "address.citySuffix", label: "City Suffix" },
    { stub: "address.streetName", label: "Street Name" },
    { stub: "address.streetAddress", label: "Street Address" },
    { stub: "address.streetSuffix", label: "Street Suffix" },
    { stub: "address.streetPrefix", label: "Street Prefix" },
    { stub: "address.secondaryAddress", label: "Secondary Address" },
    { stub: "address.county", label: "County" },
    { stub: "address.country", label: "Country" },
    { stub: "address.countryCode", label: "Country Code" },
    { stub: "address.state", label: "State" },
    { stub: "address.stateAbbr", label: "State Abbreviation" },
    { stub: "address.latitude", label: "Latitude" },
    { stub: "address.longitude", label: "Longitude" }
  ],
  commerce: [
    { stub: "commerce.color", label: "Color" },
    { stub: "commerce.department", label: "Department" },
    { stub: "commerce.productName", label: "Product Name" },
    { stub: "commerce.price", label: "Price" },
    { stub: "commerce.productAdjective", label: "Product Adjective" },
    { stub: "commerce.productMaterial", label: "Product Material" },
    { stub: "commerce.product", label: "Product" }
  ],
  company: [
    { stub: "company.suffixes", label: "Suffixes" },
    { stub: "company.companyName", label: "Company Name" },
    { stub: "company.companySuffix", label: "Company Suffix" },
    { stub: "company.catchPhrase", label: "Catch Phrase" },
    { stub: "company.bs", label: "B.S." },
    { stub: "company.catchPhraseAdjective", label: "Catch Phrase Adjective" },
    { stub: "company.catchPhraseDescriptor", label: "Catch Phrase Descriptor" },
    { stub: "company.catchPhraseNoun", label: "Catch Phrase Noun" },
    { stub: "company.bsAdjective", label: "B.S. Adjective" },
    { stub: "company.bsBuzz", label: "B.S. Buzzword" },
    { stub: "company.bsNoun", label: "B.S. Noun" }
  ],
  database: [
    { stub: "database.column", label: "Column" },
    { stub: "database.type", label: "Type" },
    { stub: "database.collation", label: "Collation" },
    { stub: "database.engine", label: "Engine" }
  ],
  date: [
    { stub: "date.past", label: "Past" },
    { stub: "date.future", label: "Future" },
    { stub: "date.between", label: "Between" },
    { stub: "date.recent", label: "Recent" },
    { stub: "date.soon", label: "Soon" },
    { stub: "date.month", label: "Month" },
    { stub: "date.weekday", label: "Weekday" }
  ],
  finance: [
    { stub: "finance.account", label: "Account" },
    { stub: "finance.accountName", label: "Account Name" },
    { stub: "finance.mask", label: "Mask" },
    { stub: "finance.amount", label: "Account" },
    { stub: "finance.transactionType", label: "Transaction Type" },
    { stub: "finance.currencyCode", label: "Currency Code" },
    { stub: "finance.currencyName", label: "Currency Name" },
    { stub: "finance.currencySymbol", label: "Currency Symbol" },
    { stub: "finance.bitcoinAddress", label: "Bitcoin Address" },
    { stub: "finance.ethereumAddress", label: "Ethereum Address" },
    { stub: "finance.iban", label: "IBAN" },
    { stub: "finance.bic", label: "BIC" }
  ],
  hacker: [
    { stub: "haker.abbreviation", label: "Abbreviation" },
    { stub: "haker.adjective", label: "Adjective" },
    { stub: "haker.noun", label: "Noun" },
    { stub: "haker.verb", label: "Verb" },
    { stub: "haker.ingverb", label: "-ing Verb" },
    { stub: "haker.phrase", label: "Phrase" }
  ],
  image: [
    { stub: "image.image", label: "Image" },
    { stub: "image.avatar", label: "Avatar" },
    { stub: "image.imageUrl", label: "Image Url" },
    { stub: "image.abstract", label: "Abstract" },
    { stub: "image.animals", label: "Animals" },
    { stub: "image.business", label: "Business" },
    { stub: "image.cats", label: "Cats" },
    { stub: "image.city", label: "City" },
    { stub: "image.food", label: "Food" },
    { stub: "image.nightlife", label: "Nightlife" },
    { stub: "image.fashion", label: "Fashion" },
    { stub: "image.people", label: "People" },
    { stub: "image.nature", label: "Nature" },
    { stub: "image.sports", label: "Sports" },
    { stub: "image.technics", label: "Technics" },
    { stub: "image.transport", label: "Transport" },
    { stub: "image.dataUri", label: "Data URI" }
  ],
  internet: [
    { stub: "internet.avatar", label: "Avatar" },
    { stub: "internet.email", label: "Email" },
    { stub: "internet.exampleEmail", label: "Example Email" },
    { stub: "internet.userName", label: "User Name" },
    { stub: "internet.protocol", label: "Protocol" },
    { stub: "internet.url", label: "URL" },
    { stub: "internet.domainName", label: "Domain Name" },
    { stub: "internet.domainSuffix", label: "Domain Suffix" },
    { stub: "internet.domainWord", label: "Domain Word" },
    { stub: "internet.ip", label: "IP" },
    { stub: "internet.ipv6", label: "IPV6" },
    { stub: "internet.userAgent", label: "User Agent" },
    { stub: "internet.color", label: "Color" },
    { stub: "internet.mac", label: "Mac" },
    { stub: "internet.password", label: "Password" }
  ],
  lorem: [
    { stub: "lorem.word", label: "Word" },
    { stub: "lorem.words", label: "Words" },
    { stub: "lorem.sentence", label: "Sentence" },
    { stub: "lorem.slug", label: "Slug" },
    { stub: "lorem.sentences", label: "Sentences" },
    { stub: "lorem.paragraph", label: "Paragraph" },
    { stub: "lorem.paragraphs", label: "Paragraphs" },
    { stub: "lorem.text", label: "Text" },
    { stub: "lorem.lines", label: "Lines" }
  ],
  name: [
    { stub: "name.firstName", label: "First Name" },
    { stub: "name.lastName", label: "Last Name" },
    { stub: "name.findName", label: "Full Name" },
    { stub: "name.jobTitle", label: "Job Titile" },
    { stub: "name.prefix", label: "Prefix" },
    { stub: "name.suffix", label: "Suffix" },
    { stub: "name.title", label: "Title" },
    { stub: "name.jobDescriptor", label: "Job Descriptor" },
    { stub: "name.jobArea", label: "Job Area" },
    { stub: "name.jobType", label: "Job Type" }
  ],
  phone: [
    { stub: "phone.phoneNumber", label: "Phone Number" },
    { stub: "phone.phoneNumberFormat", label: "Phone Number Format" },
    { stub: "phone.phoneFormats", label: "Phone Formats" }
  ],
  random: [
    { stub: "random.number", label: "Number" },
    { stub: "random.float", label: "Float" },
    { stub: "random.arrayElement", label: "Array Element" },
    { stub: "random.objectElement", label: "Object Element" },
    { stub: "random.uuid", label: "UUID" },
    { stub: "random.boolean", label: "Boolean" },
    { stub: "random.word", label: "Word" },
    { stub: "random.words", label: "Words" },
    { stub: "random.image", label: "Image" },
    { stub: "random.locale", label: "Locale" },
    { stub: "random.alphaNumeric", label: "Alphanumeric" },
    { stub: "random.hexaDecimal", label: "Hexadecimal" }
  ],
  system: [
    { stub: "system.fileName", label: "Filename" },
    { stub: "system.commonFileName", label: "Common Filename" },
    { stub: "system.mimeType", label: "MIME Type" },
    { stub: "system.commonFileType", label: "Common File Type" },
    { stub: "system.commonFileExt", label: "Common File Extension" },
    { stub: "system.fileType", label: "File Type" },
    { stub: "system.fileExt", label: "File Extension" },
    { stub: "system.directoryPath", label: "Directory Path" },
    { stub: "system.filePath", label: "File Path" },
    { stub: "system.semver", label: "Semver" }
  ]
};
